### ISSUE TITLE
Link to the study?

### ISSUE THREAD

**Issue by neuhaus** [RUB-SysSec/be-the-phisher#1]
Could you provide a link to the study please?

**Comment by RUB-SysSec** [comment]
The repository contains the source code of a web application we used about two years ago to analyze whether creating own phishing domains helps users to identify actual phishing domains. However, the web application is not online anymore because we finished the study. If you are interested in the results, take a look at the paper [1] or the data in survey_tool/data/results. If you want to see how the web application looked like, feel free to clone the repository and follow the instructions in README.md to run it locally on your computer.

[1] https://www.syssec.ruhr-uni-bochum.de/research/publications/be-phisher-understanding-users-perception-maliciou/
